# Generated by Django 4.2.5 on 2024-11-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='administracaopredial',
            name='predio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administracao', to='reservas.predio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='reservas.predio'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.predio'),
        ),
    ]
