# Generated by Django 4.2.5 on 2024-11-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_predio_administracaopredial_predio_alter_sala_predio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_administracao_predial',
            new_name='is_building_administrator',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_grupo_extensao',
            new_name='is_normal_user',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
