# Generated by Django 4.2.5 on 2024-11-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_is_administracao_predial_usuario_is_building_administrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_normal_user',
            new_name='is_grupo_extensao',
        ),
    ]
