# Generated by Django 4.2.5 on 2024-11-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_is_normal_user_usuario_is_grupo_extensao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_grupo_extensao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_representante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_representante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='duracao',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='GrupoExtensao',
        ),
    ]
